### PR TITLE
brands 

### LINKED ISSUE #86: Brands/Logos
### Link to Icon Pack

- https://github.com/jpswalsh/academicons/tree/master/svg
- https://github.com/ryanoasis/nerd-fonts/tree/master/src/svgs
- https://github.com/atisawd/boxicons/tree/master/svg/logos
- https://github.com/coreui/coreui-icons/tree/main/svg/brand
- https://github.com/spothq/cryptocurrency-icons/tree/master/svg/black
- https://github.com/devicons/devicon/tree/master/icons
- https://github.com/FortAwesome/Font-Awesome/tree/6.x/svgs/brands
- https://github.com/lukas-w/font-logos/tree/master/vectors
- https://github.com/datatrans/payment-logos/tree/master/assets
- https://github.com/Remix-Design/RemixIcon/tree/master/icons/Logos
- https://icofont.com/

### Reason for Addition

I noticed that many of the icon packs have the same brand icons. To avoid redundancy and make better use of the available Unicode space, IconicFonts should consider consolidating these icons into a single, unified pack. This approach would help prevent duplicate icons in the patched fonts and also conserve Unicode slots, given the 65,535 glyph limit per font.

### Additional Information

Some of the packs might be removed from the patched fonts entirely, like...

- [Academicons](https://github.com/jpswalsh/academicons)
- [Cryptocurrency](https://github.com/spothq/cryptocurrency-icons)
- [devicon](https://github.com/devicons/devicon)
- [font-logos](https://github.com/Lukas-W/font-logos)
- [payment-logos](https://github.com/datatrans/payment-logos)

### PR DESCRIPTION
**Pull request by ghost**
Resolves #86

### CODE REVIEW

**Comment by shadowgaming-backup** [comment]
The brands are from font awesome, i have not made any changes to it still @mdSlash

**Comment by shadowgaming-backup** [comment]
the bash script is does not give any output, should i creates folders inside brands to show where i got it from

**Comment by shadowgaming-backup** [comment]
have not still used inkscape

**Comment by mdSlash** [comment]
Awesome, thanks for your effort! There’s just a small modification needed: please capitalize `brand` to `Brands` and move the `.svg` files to the `svgs` directory inside `Brands`.

**Comment by mdSlash** [comment]
> the bash script is does not give any output, should i creates folders inside brands to show where i got it from

If there is no output, it means all the icons are solid and do not need to be converted.

**Comment by shadowgaming-backup** [comment]
> > have not still used inkscape
> > Yes, cause the icons are solid.

OK, should I create a font awesome folder and pass all svgs files to there

**Comment by shadowgaming-backup** [comment]
I will make/find a script that it will prevent duplication,
Mostly will need to do a manual review to check

**Comment by mdSlash** [comment]
The Brand Pack should have a single folder called "svgs" with all the icons inside, just like the structure of the other packs. It might get a bit tricky because there are many icons with the same name and others with different names but similar designs. So, we’ll need to manually review and sort them out.

If you find icons with the same name but different designs, add a number to the end of the file name to differentiate them. For example, if the first one `x.svg` the second one `x-1.svg` the third one `x-2.svg` and so on.

Sorry for the lack of information and tools so far. I didn’t expect contributors to come on board so soon, so I’m still working on getting everything organized.

**Comment by mdSlash** [comment]
If you find it takes too long to sort things out, feel free to keep your current PR as it is for now.

**Comment by shadowgaming-backup** [comment]
> The Brand Pack should have a single folder called "svgs" with all the icons inside, just like the structure of the other packs. It might get a bit tricky because there are many icons with the same name and others with different names but similar designs. So, we’ll need to manually review and sort them out.

Ok
> 
> If you find icons with the same name but different designs, add a number to the end of the file name to differentiate them. For example, if the first one `x.svg` the second one `x-1.svg` the third one `x-2.svg` and so on.
> 
We can split the work 
When you are free you can check and when yjh stop make sure to reply where you stop so we do not review it twice 

> Sorry for the lack of information and tools so far. I didn’t expect contributors to come on board so soon, so I’m still working on getting everything organized.

No problem, I even am not actively working on it. Can you make changes to it or should I invite you to the repo

**Comment by shadowgaming-backup** [comment]
If you are free you can help on review it depends on you

**Comment by shadowgaming-backup** [comment]
There is going to be a brands folder so shouldn't remove brands svg from others folders

**Comment by mdSlash** [comment]
I’m not currently working on it, but I will be soon. In the meantime, you can go ahead and put the icons in the "svgs" directory and rename "brands" to "Brands" before submitting your PR. I’ll continue from there once it’s in place. Thanks!

**Comment by shadowgaming-backup** [comment]
https://github.com/shadowgaming-backup/if/blob/main/packs/Brands/apple-pay.svg
https://github.com/shadowgaming-backup/if/blob/main/packs/Brands/cc-apple-pay.svg

There are the same logos but presented in a different way which do you prefer

**Comment by shadowgaming-backup** [comment]
> I’m not currently working on it, but I will be soon. In the meantime, you can go ahead and put the icons in the "svgs" directory and rename "brands" to "Brands" before submitting your PR. I’ll continue from there once it’s in place. Thanks!

I have renamed to Brands 
And added all svg inside packs/Brands folder

**Comment by mdSlash** [comment]
> There are the same logos but presented in a different way which do you prefer

Both because the two designs have different styles

**Comment by mdSlash** [comment]
> I have renamed to Brands And added all svg inside packs/Brands folder

Just like other packs, `.svg` files should go inside the `PackName/svgs` directory, not in the `PackName/` directory

**Comment by shadowgaming-backup** [comment]
> > I have renamed to Brands And added all svg inside packs/Brands folder
> 
> Just like other packs, `.svg` files should go inside the `PackName/svgs` directory, not in the `PackName/` directory

I am doing that, and I will be downloading other brands icon pack and i will run a script that checks for the same name

**Pull request merged**
